# See https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy NextJS Website

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Packages
        run: npm ci

      - name: Build and Export
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.4.1
        with:
          # Branch the action should deploy to
          BRANCH: gh-pages
          # Folder the action should deploy to
          FOLDER: out